### ISSUE TITLE
Python doesn't install 3rd parties

### ISSUE THREAD

**Issue by jinho-youha** [ScottBrenner/aws-cdk-action#19]
Hey, suddenly latest version doesn't install the python 3rd parties. So our CI pipeline got broken. 

In my research, you should change `entrypoint.sh` like the following. Please remove `!` in the if condition. 

```bash
#!/bin/sh

set -e

if [  -f "requirements.txt" ]; then
  pip3 install -r requirements.txt
fi

sh -c "cdk $*"
```

**Comment by ScottBrenner** [comment]
Oops, thanks for reporting!
